FROM amazon/opendistro-for-elasticsearch:0.7.0

# Install kuromoji
RUN elasticsearch-plugin install analysis-kuromoji
# RUN elasticsearch-plugin install org.codelibs:elasticsearch-analysis-kuromoji-neologd:6.5.1