FROM amazon/opendistro-for-elasticsearch-kibana:0.7.0

# https://github.com/johtani/analyze-api-ui-plugin
# RUN ./bin/kibana-plugin install https://github.com/johtani/analyze-api-ui-plugin/releases/download/6.5.4/analyze-api-ui-plugin-6.5.4.zip
