version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-cluster-network
  kafka:
    image: confluentinc/cp-kafka:5.1.3
    depends_on:
      - zookeeper
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    networks:
      - kafka-cluster-network
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.1.3
    depends_on:
      - kafka
    container_name: kafkarest
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_HOST_NAME: "kafkarest"
      KAFKA_REST_LISTENERS: "http://kafkarest:8082"
    networks:
      - kafka-cluster-network
  kafka-topic-ui:
    image: landoop/kafka-topics-ui:0.9.4
    depends_on:
        - kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: "http://kafkarest:8082"
      PROXY: "true"
    ports:
      - "8000:8000"
    networks:
      - kafka-cluster-network

networks:
  kafka-cluster-network:
